### ISSUE TITLE
Intersection of CMap and PFOCR extracted chemicals

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pathway-figure-ocr#25]
In our shared NIA folder, this file has >6000 drugs annotated for repurposing: CMap_Repurposing_Hub.xlsx

Can you add a column to this table (or create a separate mapping table) based on the intersection of names?

There are no mappings from MeSH to BRD ID, unfortunately, so let's just see what we can get from a simple name match for now. I acknowledge that this will miss a lot of things.

**Comment by AlexanderPico** [comment]
Here's a second list of drug names to attempt a quick intersection with:
https://www.dropbox.com/s/taia99vu2tah6cy/Full%20Library%20Gladstone%20%28with%20cpd%20names%29_20171106.xlsx?dl=0

**Comment by ariutta** [comment]
First batch:
https://www.dropbox.com/s/je6e3q513p5ql3p/CMap_Repurposing_Hub_PFOCR.xlsx?dl=0

**Comment by ariutta** [comment]
Second batch:
https://www.dropbox.com/s/ohu9k2on8yflydc/Full%20Library%20Gladstone%20%28with%20cpd%20names%29_20171106_PFOCR.xlsx?dl=0

**Comment by AlexanderPico** [comment]
PFOCR overlaps:

- 1267 of 6798 CMap
- 1025 of 6912 Anke's library

**Comment by ariutta** [comment]
Code used:
https://github.com/wikipathways/pathway-figure-ocr/blob/master/notebooks/chemical_intersections.ipynb

**Comment by ariutta** [comment]
pfocr_id's for CMap: 13,575
pfocr_id's for Anke: 10,045
