### ISSUE TITLE
New gene counts

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pathway-figure-ocr#26]
- number of total gene mentions, expected ~1.4 million
- number of total unique genes, expected ~14k
- number of total non-redundant pathways, expected ~81k

**Comment by ariutta** [comment]
* number of total gene mentions: 1,326,706
* number of total unique genes: 14,251
* number of total non-redundant pathways: 79,949 (having at least one recognized gene: 73,878)

**Comment by AlexanderPico** [comment]
Diffs for new counts:
- 214,155 new mentions
- 787 new unique genes
- 15,306 new figures
