### ISSUE TITLE
MSigDb unique gene count

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pathway-figure-ocr#27]
This page (https://www.gsea-msigdb.org/gsea/msigdb/genesets.jsp?collection=C2) has 11 signatures with "Alzheimer" in their name.

Click on each to find a "download gene set" option, e.g., GMT and TXT formats.

Can you help get a count for **unique** genes across these 11 sets?

**Comment by AlexanderPico** [comment]
these signatures contain only 3,077 unique genes

**Comment by AlexanderPico** [comment]
Let's just count the C2/CP collection. The other "CGP" sets are just DE gene lists from perturbation experiments and are thus not comparable to curated pathways.

https://www.gsea-msigdb.org/gsea/msigdb/genesets.jsp?collection=CP

**Comment by khanspers** [comment]
There are 4 sets in C2_CP for Alzheimers, from 4 sources (WP, KEGG, BIOCARTA and REACTOME). 
Total unique genes 89.
Spreadsheet here: https://www.dropbox.com/s/2hel6rllbsj0juf/MSigDB_Counts_C2-CP.xlsx?dl=0
And screenshot of the summary here:
<img width="384" alt="Screen Shot 2021-05-27 at 4 44 12 PM" src="https://user-images.githubusercontent.com/1442197/119909876-cb84fa80-bf0a-11eb-817c-a1d2fcab5d38.png">

**Comment by AlexanderPico** [comment]
Wait, how are the total unique only 89 when KEGG and WP each have 166 and 150?

**Comment by khanspers** [comment]
<img width="380" alt="Screen Shot 2021-05-28 at 10 01 17 AM" src="https://user-images.githubusercontent.com/1442197/120018196-aab8b580-bf9b-11eb-94da-fbf4c740c024.png">
